import {sqliteAdapter} from '../scripts/sqlite-adapter.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {api} from '../server/index.js';
const directory=mkdtempSync(join(tmpdir(),'cng-test-'));const path=join(directory,'db.sqlite');let sqlite=new DatabaseSync(path);
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sqlite.exec(readFileSync(`drizzle/${f}`,'utf8'));
const env={DB:sqliteAdapter(()=>sqlite)};
async function call(user,path,method='GET',body,origin='https://cng.test'){const headers={};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=`${user}@example.test`;}if(body){headers['Content-Type']='application/json';headers.Origin=origin;}const r=await api(new Request(`https://cng.test/api${path}`,{method,headers,body:body?JSON.stringify(body):undefined}),env);return{status:r.status,...await r.json()};}
const station={name:'Test CNG Station',city:'Dondaicha',address:'Test road, Dondaicha',status:'Open',pricePerKg:94.5,gasPressure:210,nozzles:2,operatingHours:'06:00–22:00',supportedVehicles:['Car','Commercial']};
const payload=id=>({stationId:id,driverName:'Test Driver',phone:'9876543210',vehicleType:'Car',vehicleNo:'MH18AB1234',refillQty:'Full tank',requestKey:crypto.randomUUID()});
test('authenticated booking lifecycle, isolation, validation and durable data',async()=>{try{
 assert.equal((await call(null,'/state')).status,401);
 assert.equal((await call('operator','/stations','POST',station,'https://evil.test')).status,403);
 const created=await call('operator','/stations','POST',station);assert.equal(created.status,201);const sid=created.id;
 assert.equal((await call('stranger',`/stations/${sid}`,'PATCH',station)).status,403);
 assert.equal((await call('driver','/bookings','POST',{...payload(sid),phone:'bad'})).status,400);
 const body=payload(sid),booking=await call('driver','/bookings','POST',body);assert.equal(booking.status,201);
 assert.equal((await call('driver','/bookings','POST',body)).id,booking.id);
 assert.equal((await call('driver','/bookings','POST',payload(sid))).status,409);
 assert.equal((await call('stranger','/state')).bookings.length,0);
 assert.equal((await call('stranger',`/bookings/${booking.id}/status`,'PATCH',{status:'Cancelled'})).status,403);
 assert.equal((await call('driver',`/bookings/${booking.id}/status`,'PATCH',{status:'Completed'})).status,403);
 assert.equal((await call('operator',`/bookings/${booking.id}/status`,'PATCH',{status:'Completed'})).status,409);
 assert.equal((await call('operator',`/stations/${sid}/next`,'POST',{})).status,200);
 assert.equal((await call('driver',`/bookings/${booking.id}/status`,'PATCH',{status:'Cancelled'})).status,409);
 assert.equal((await call('operator',`/bookings/${booking.id}/status`,'PATCH',{status:'Completed'})).status,200);
 assert.equal((await call('operator',`/bookings/${booking.id}/status`,'PATCH',{status:'In Progress'})).status,409);
 assert.equal((await call('driver','/state')).stations[0].queueCount,0);
 await call('driver',`/favorites/${sid}`,'PUT',{saved:true});
 sqlite.close();sqlite=new DatabaseSync(path);
 const restored=await call('driver','/state');assert.equal(restored.bookings[0].status,'Completed');assert.deepEqual(restored.favorites,[sid]);
 const future=await call('driver','/bookings','POST',{...payload(sid),scheduledAt:new Date(Date.now()+3600000).toISOString()});assert.equal(future.status,201);
 assert.equal((await call('operator',`/stations/${sid}/next`,'POST',{})).status,409);
 assert.equal((await call('operator',`/bookings/${future.id}/status`,'PATCH',{status:'In Progress'})).status,409);
 assert.equal((await call('driver',`/bookings/${future.id}/status`,'PATCH',{status:'Cancelled'})).status,200);
 await call('operator',`/stations/${sid}`,'PATCH',{...station,status:'Closed'});
 assert.equal((await call('driver','/bookings','POST',payload(sid))).status,409);
 assert.equal((await call('driver','/bookings','POST',{...payload(sid),status:'Completed',userId:'operator'})).status,409);
 }finally{sqlite.close();rmSync(directory,{recursive:true,force:true});}});
