import React,{useState,useRef} from 'react';
import {X} from 'lucide-react';
import {VEHICLE_TYPES} from '../data/mockStations';
import useModal from '../utils/useModal';
export default function BookingModal({station,onClose,onSubmitBooking}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[scheduled,setScheduled]=useState(false);const key=useRef(crypto.randomUUID());const modal=useModal(onClose);
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));try{await onSubmitBooking({...f,stationId:station.id,requestKey:key.current,scheduledAt:scheduled?new Date(f.scheduledAt).toISOString():null});}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <div className="modal-overlay"><div ref={modal} className="modal-content" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="modal-close" onClick={onClose} aria-label="Close"><X/></button><h2 id="booking-title">Book your refill</h2><p>{station.name}</p><p className="muted">₹{station.pricePerKg}/kg · {station.queueCount} in queue</p>{error&&<p className="error-banner" role="alert">{error}</p>}<form onSubmit={submit}><div className="form-grid"><label>Driver name<input className="form-input" name="driverName" required minLength={2} maxLength={80} autoComplete="name"/></label><label>Mobile number<input className="form-input" name="phone" type="tel" required maxLength={20} placeholder="9876543210" autoComplete="tel"/></label><label>Vehicle number<input className="form-input" name="vehicleNo" required minLength={5} maxLength={20} placeholder="MH 18 AB 1234"/></label><label>Vehicle type<select className="form-select" name="vehicleType">{VEHICLE_TYPES.filter(v=>station.supportedVehicles.includes(v.id)).map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label></div><label>Refill preference<select name="refillQty" className="form-select"><option>Full tank</option><option>5 kg</option><option>₹500</option><option>₹1000</option></select></label><label className="check-row"><input type="checkbox" checked={scheduled} onChange={e=>setScheduled(e.target.checked)}/>Schedule for later</label>{scheduled&&<label>Arrival date and time<input className="form-input" type="datetime-local" name="scheduledAt" required/><small>Up to 7 days ahead, in your device’s timezone.</small></label>}<p className="muted">The station operator can see these details to serve your booking. Payment is handled at the station.</p><button className="btn btn-primary" disabled={busy} type="submit">{busy?'Saving booking…':'Confirm booking'}</button></form></div></div>;
}
