import React,{useState} from 'react';
import {VEHICLE_TYPES} from '../data/mockStations';
function StationForm({station,onSave,onClose,busy}){
 const[error,setError]=useState('');
 async function submit(e){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const b={name:f.get('name'),city:f.get('city'),address:f.get('address'),pricePerKg:Number(f.get('price')),gasPressure:Number(f.get('pressure')),nozzles:Number(f.get('nozzles')),status:f.get('status'),operatingHours:f.get('hours'),supportedVehicles:f.getAll('vehicles')};try{await onSave(b);onClose();}catch(err){setError(err.message);}}
 return <form onSubmit={submit} className="glass-card station-form"><h2>{station?'Edit station':'Register your station'}</h2><p>Only register stations you manage. The details you enter will be shown to signed-in visitors.</p>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="form-grid"><label>Station name<input name="name" className="form-input" defaultValue={station?.name} required minLength={3} maxLength={120}/></label><label>City<input name="city" className="form-input" defaultValue={station?.city} placeholder="Dondaicha" required minLength={2} maxLength={60}/></label><label className="full-width">Address<input name="address" className="form-input" defaultValue={station?.address} required minLength={5} maxLength={250}/></label><label>CNG price (₹/kg)<input type="number" step="0.01" min="1" max="500" name="price" className="form-input" defaultValue={station?.pricePerKg} required/></label><label>Pressure (bar)<input type="number" min="0" max="400" name="pressure" className="form-input" defaultValue={station?.gasPressure} required/></label><label>Working nozzles<input type="number" min="1" max="30" name="nozzles" className="form-input" defaultValue={station?.totalNozzles||1} required/></label><label>Station status<select name="status" className="form-select" defaultValue={station?.status||'Open'}><option>Open</option><option>Closed</option></select></label><label className="full-width">Operating hours<input name="hours" className="form-input" defaultValue={station?.operatingHours||'06:00–22:00'} maxLength={100} required/></label></div><fieldset><legend>Supported vehicles</legend>{VEHICLE_TYPES.map(v=><label className="check-row" key={v.id}><input type="checkbox" name="vehicles" value={v.id} defaultChecked={station?station.supportedVehicles.includes(v.id):true}/>{v.name}</label>)}</fieldset><div className="button-row"><button disabled={busy} className="btn btn-primary">{busy?'Saving…':'Save station'}</button><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button></div></form>;
}
export default function OperatorDashboard({stations,bookings,busy,onCreate,onUpdate,onCallNext,onUpdateBookingStatus}){
 const[selected,setSelected]=useState(''),[editing,setEditing]=useState(false),[adding,setAdding]=useState(false),[token,setToken]=useState(''),[feedback,setFeedback]=useState('');const station=stations.find(s=>s.id===selected)||stations[0];
 const rows=bookings.filter(b=>b.stationId===station?.id);const waiting=rows.filter(b=>['Active','In Progress'].includes(b.status));
 const act=async(fn,message)=>{setFeedback('');try{await fn();setFeedback(message);}catch(e){setFeedback(e.message);}};
 return <section><div className="page-heading"><span className="badge badge-primary">OPERATOR WORKSPACE</span><h1>My stations</h1><p>Keep details current and serve tokens in order.</p></div><div className="button-row"><select className="form-select" aria-label="Managed station" value={station?.id||''} onChange={e=>{setSelected(e.target.value);setEditing(false);setFeedback('');}}>{!stations.length&&<option value="">No station yet</option>}{stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="btn btn-primary" onClick={()=>{setAdding(true);setEditing(false);}}>Register station</button>{station&&<button className="btn btn-secondary" onClick={()=>{setEditing(!editing);setAdding(false);}}>Edit details</button>}</div>
 {(adding||editing)&&<StationForm key={adding?'new':station.id} station={adding?null:station} busy={busy} onSave={adding?onCreate:b=>onUpdate(station.id,b)} onClose={()=>{setAdding(false);setEditing(false);}}/>}
 {!station&&!adding&&<div className="glass-card empty-state"><h2>Start accepting bookings</h2><p>Register your station’s address, rate, pressure and working hours. You’ll manage only the stations registered by your account.</p></div>}
 {station&&<><div className="operator-stats"><div className="glass-card"><span>Station</span><strong>{station.status}</strong></div><div className="glass-card"><span>Due queue</span><strong>{station.queueCount}</strong></div><div className="glass-card"><span>CNG rate</span><strong>₹{station.pricePerKg}/kg</strong></div></div><div className="glass-card"><h2>Serve next customer</h2><p>Calls the earliest due token. Future reservations stay scheduled.</p><button disabled={busy||station.status!=='Open'} className="btn btn-primary" onClick={()=>act(()=>onCallNext(station.id),'Next token called.')}>Call next token</button><form className="button-row token-search" onSubmit={e=>{e.preventDefault();const b=rows.find(b=>b.id===token.trim()||b.tokenNo===token.trim().toUpperCase());setFeedback(b?`${b.tokenNo}: ${b.driverName} · ${b.vehicleNo} · ${b.status}`:'Token not found at this station.');}}><input className="form-input" aria-label="Token or QR value" placeholder="Enter token number or scanned QR value" value={token} onChange={e=>setToken(e.target.value)}/><button className="btn btn-secondary">Find token</button></form>{feedback&&<p role="status">{feedback}</p>}</div>
 <h2 className="section-title">Waiting & scheduled ({waiting.length})</h2><div className="booking-list">{waiting.slice().reverse().map(b=><div className="glass-card booking-row" key={b.id}><div><span className="badge badge-primary">{b.tokenNo} · {b.status}</span><h3>{b.vehicleNo} · {b.driverName}</h3><p>{b.phone} · {b.refillQty}</p><p>{new Date(b.scheduledAt).toLocaleString()}</p></div><div className="button-row">{b.status==='Active'?<><button disabled={busy||!b.due||station.status!=='Open'} className="btn btn-primary" onClick={()=>act(()=>onUpdateBookingStatus(b.id,'In Progress'),'Token called.')}>Start refill</button><button disabled={busy} className="btn btn-secondary" onClick={()=>act(()=>onUpdateBookingStatus(b.id,'Cancelled'),'Booking cancelled.')}>Cancel</button></>:<button disabled={busy} className="btn btn-primary" onClick={()=>act(()=>onUpdateBookingStatus(b.id,'Completed'),'Refill completed.')}>Complete refill</button>}</div></div>)}</div>{!waiting.length&&<p className="empty-state">No waiting bookings.</p>}<details className="glass-card"><summary>Completed & cancelled bookings ({rows.length-waiting.length})</summary>{rows.filter(b=>!['Active','In Progress'].includes(b.status)).map(b=><p key={b.id}>{b.tokenNo} · {b.vehicleNo} · {b.status}</p>)}</details></>}
 </section>;
}
