import React,{useState} from 'react';
import {Search,Gauge,Heart} from 'lucide-react';
import StationCard from './StationCard';
import {VEHICLE_TYPES} from '../data/mockStations';
export default function StationFinder({stations,selectedCity,onBookStation,favorites,onToggleFavorite}){
 const[q,setQ]=useState(''),[vehicle,setVehicle]=useState('All'),[pressure,setPressure]=useState(false),[saved,setSaved]=useState(false);
 const filtered=stations.filter(s=>(selectedCity==='All cities'||s.city===selectedCity)&&`${s.name} ${s.city} ${s.address}`.toLowerCase().includes(q.toLowerCase())&&(vehicle==='All'||s.supportedVehicles.includes(vehicle))&&(!pressure||s.gasPressure>=210)&&(!saved||favorites.includes(s.id)));
 return <section><div className="page-heading"><span className="badge badge-primary">STATION FINDER</span><h1>Find your next refill.</h1><p>Choose a station, check the queue and book a token.</p></div><div className="glass-card filter-bar"><label className="search-field"><Search size={18}/><input aria-label="Search stations" className="form-input" placeholder="Search station, city or address" value={q} onChange={e=>setQ(e.target.value)}/></label><select className="form-select" aria-label="Vehicle type" value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="All">All vehicles</option>{VEHICLE_TYPES.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><button aria-pressed={pressure} className={`btn ${pressure?'btn-primary':'btn-secondary'}`} onClick={()=>setPressure(!pressure)}><Gauge size={16}/>210+ bar</button><button aria-pressed={saved} className={`btn ${saved?'btn-primary':'btn-secondary'}`} onClick={()=>setSaved(!saved)}><Heart size={16}/>Saved</button></div><p className="results-count">{filtered.length} station{filtered.length===1?'':'s'}</p><div className="station-grid">{filtered.map(s=><StationCard key={s.id} station={s} onBook={onBookStation} isFavorite={favorites.includes(s.id)} onToggleFavorite={onToggleFavorite}/>)}</div>{stations.length>0&&!filtered.length&&<p className="empty-state">No matching stations. Try another city or remove a filter.</p>}</section>;
}
